### ISSUE TITLE
markdown渲染问题

### ISSUE THREAD

**Issue by zyoung1212** [linhaojun857/aurora#119]
给了一段文字居中，但是发布文章后，显示有问题
同样的问题还有右对齐、角标等。
![image](https://github.com/linhaojun857/aurora/assets/20473104/1f331452-bde2-4e14-ae07-b27f3149da29)

![image](https://github.com/linhaojun857/aurora/assets/20473104/d63c0bd4-748f-4911-9a18-8202ea16d11b)

**Comment by linhaojun857** [comment]
前台的markdown解析问题，后面会修复，欢迎pr

**Comment by ling-1** [comment]
> 前台的markdown解析问题，后面会修复，欢迎pr

原生markdown是不支持居中、对齐操作的，但是很多编辑器如mavon-editor提供了支持，该项目前台markdown渲染器并不完全支持mavon-editor提供的语法，可用html自行渲染或者使用通标准的渲染器进行渲染。之后我会提交pr，请留意。

**Comment by linhaojun857** [comment]
> > 前台的markdown解析问题，后面会修复，欢迎pr
> 
> 原生markdown是不支持居中、对齐操作的，但是很多编辑器如mavon-editor提供了支持，该项目前台markdown渲染器并不完全支持mavon-editor提供的语法，可用html自行渲染或者使用通标准的渲染器进行渲染。之后我会提交pr，请留意。

感谢，pr麻烦提交到dev分支
