### ISSUE TITLE
复制过来的样式和主题，写一下出去呀

### ISSUE THREAD

**Issue by bennyxguo** [linhaojun857/aurora#133]
主题来源：https://github.com/auroral-ui/hexo-theme-aurora
所有样式移植过来了，至少也要写一下来源呀

可以看看 commit log，我的代码很早之前就有了。

你这感谢了 网盾星球，Jetbrains，也提一下我写的主题来源。

**Comment by linhaojun857** [comment]
![image](https://github.com/linhaojun857/aurora/assets/98197853/2f919984-3dba-4dbe-a39f-750c2656a431)
