### ISSUE TITLE
哪里copy的项目

### ISSUE THREAD

**Issue by jiurang** [linhaojun857/aurora#172]
一堆问题跑不起来也敢放上来，一个pom文件连parent都没有，还放一堆依赖。。看来是要修你这破博客了，

**Comment by linhaojun857** [comment]
部署文档写的明明白白的，看不懂？？？实在不行进群问，用个别人东西还在这哔哔

**Comment by jiurang** [comment]
![image](https://github.com/linhaojun857/aurora/assets/97287369/f52fb06b-d552-4285-8820-51e9df575d46)
![image](https://github.com/linhaojun857/aurora/assets/97287369/aa214905-29b9-4ff9-b86d-c41eee3581ee)
这就是你的部署文档，不是我哔哔，确实是你搞得太烂了，我看了好几个博客项目，代码跟你这个差不多，除了博客的前端，搞得烂说你咋滴？？

**Comment by linhaojun857** [comment]
你node和npm版本换对了吗？（部署文档看了吗？？？），就在这无脑哔哔，你有本事自己写啊？？？不用不就行了

**Comment by jiurang** [comment]
自己肯定会写的，现在没时间，有时间写一个

**Comment by linhaojun857** [comment]
6，这两个分支代码明明都一样

**Comment by jiurang** [comment]
![image](https://github.com/linhaojun857/aurora/assets/97287369/c6e98f8d-6d57-418b-bbac-80017a7590e7)这个是从master拉的，
![image](https://github.com/linhaojun857/aurora/assets/97287369/ca505d6c-d180-46ac-97e2-c06808085662) 你看这个pom下面一堆依赖，上面连parent都没有，
![image](https://github.com/linhaojun857/aurora/assets/97287369/1b54da5f-a6d2-4dfe-b9ba-fc8e02bb5302)这个不是文档明显跟dev不一样

**Comment by jiurang** [comment]
所以，你知道我在打开这个项目的时候有多上头了吧，现在master和dev一样，我之前看的时候可不一样

**Comment by linhaojun857** [comment]
你自己好好看一下，两个分支的提交历史，不一样吗？？？

**Comment by linhaojun857** [comment]
6

**Comment by jiurang** [comment]
我拉下来可是跟截图的一样，6

**Comment by jiurang** [comment]
我之前看的时候，你们master最早的不是两个星期，是带有years的，我忘记是多少了，我给你道个歉，虽然不知道是什么原因，但说你就是我的不对，对不起！！！！！
