### ISSUE TITLE
部署步驟好麻煩啊

### ISSUE THREAD

**Issue by changchichung** [linhaojun857/aurora#50]
能不能弄成一個 docker-compose 啊？

**Comment by linhaojun857** [comment]
我有弄成docker-compose的想法，但是一直没有时间搞，后面有时间了一定搞，如果老哥有时间的话，可不可以帮忙搞一下吗？最近实在太忙了，之前就有人反馈过这个问题

**Comment by linhaojun857** [comment]
目前手上有点事儿，后面闲下来会搞得

**Comment by terwer** [comment]
大佬可以参考我的 docker-compose，我之前写过类似的，但是界面没你好看。

https://github.com/terwer/jvue/blob/master/docker-compose.yml

宁外，xmlrpc可以参考 https://github.com/terwer/jvue/blob/master/jvue-server/src/main/java/com/terwergreen/jvueserver/coresevice/xmlrpc/MetaWeblogImpl.java

不介意的话，我抽时间给你 PR 一个也行

**Comment by linhaojun857** [comment]
加docker-compose之前我可能会优化一下技术栈，ES和MQ到时候会考虑删去，对于一个博客来说有点笨重了，感谢大佬对于项目的支持😁

**Comment by changchichung** [comment]
加油，我一開始也覺得 ES/MQ 放進來有點多餘？感覺一個blog 應該是用不到這麼大的怪物
