### ISSUE TITLE
大佬有开放的API接口么，我想集成发布功能

### ISSUE THREAD

**Issue by terwer** [linhaojun857/aurora#64]
我的思源笔记发布辅助工具，想集成发布到你的博客功能，不知道你的博客有没有提供xmlrpc的API

可以看看我的兼容情况
https://github.com/terwer/src-sy-post-publisher/blob/main/src/utils/api.ts

**Comment by linhaojun857** [comment]
暂时还没有开放的api接口，后期会考虑加入
