### ISSUE TITLE
minio文件访问bug + 前端修改建议

### ISSUE THREAD

**Issue by TlgYuri** [linhaojun857/aurora#73]
### 如：xxx.com是前台， xxx.com/admin/是后台
前端技术栈真是我知识盲区了，尝试自己改，改了好久都没改好😂

**Comment by linhaojun857** [comment]
minio推荐使用nginx代理一下  
代理的时候加上bucketName 
![image](https://user-images.githubusercontent.com/98197853/205808085-ad7c9966-fe93-42d7-ae3d-42a959a2bd9b.png)
如果不代理要在url后面加上/bucketName/ (注意要加上后面的斜杠)，但是此方法会存在一定的问题

**Comment by linhaojun857** [comment]
具体细节加Q群询问：338371628

**Comment by Zhouzzz1** [comment]
这边我在MinioUploadStrategyImpl中的重写了getFileAccessUrl方法中  加了 minioProperties.getBucketName来获取bucketName
 @Override
    public String getFileAccessUrl(String filePath) {
        return String.format("%s/%s/%s", minioProperties.getUrl(), minioProperties.getBucketName(), filePath);
    }
