### ISSUE TITLE
项目部署于2G内存+2核心服务器出现内存溢出问题

### ISSUE THREAD

**Issue by BeammNotFound** [linhaojun857/aurora#75]
在一台2G内存+2核心的服务器部署该项目，包括：
aurora-springboot-0.0.1.jar
maxwell
rabbit
mysql
redis6
会出现内存占用溢出导致服务器崩溃等异常

**Comment by BeammNotFound** [comment]
建议将mysql内存限制为500M，将aurora-springboot-0.0.1.jar限制为400M
<img width="699" alt="image" src="https://user-images.githubusercontent.com/38497714/206075051-3d40a6f4-c0fd-44b2-a64d-f707e6cfa5e8.png">
`docker update -m 500M --memory-reservation 500M --memory-swap 600M mysql`
`docker update -m 400M --memory-reservation 400M --memory-swap 500M aurora-springboot-0.0.1.jar`

**Comment by BeammNotFound** [comment]
同时可在管理平台酌情关闭功能的线程占用
![image](https://user-images.githubusercontent.com/38497714/206075536-76032666-3e43-4e8b-a09f-f3556daa4204.png)

**Comment by linhaojun857** [comment]
我觉得你可以尝试着限制其他的内存占用，最好不要限制aurora-springboot-0.0.1.jar和mysql
