### ISSUE TITLE
关于后端日志记录问题

### ISSUE THREAD

**Issue by DINGDANGMAOUP** [linhaojun857/aurora#83]
纯萌新，为何后端的日志不直接在Aspect异步记录，而要发布事件通过EventListener异步记录，这里没看懂，是有什么用意吗，求解

**Comment by Rain-ziyu** [comment]
![image](https://user-images.githubusercontent.com/70049441/223293589-03b37781-107a-4310-a21c-0760d11de415.png)
差不多是同步或者异步存储日志的区别，比如这里其实接口已经返回了，但是其实日志还没有被记录。
如果是同步的，那么必须记录日志之后才返回请求
不知道作者是不是这么考虑的
