### ISSUE TITLE
打包问题

### ISSUE THREAD

**Issue by HeadmasterEggy** [linhaojun857/aurora#97]
<img width="1711" alt="image" src="https://user-images.githubusercontent.com/93173363/233844529-8037fb6f-d6e0-424e-be7f-a75c0359ce98.png">
这个是什么问题，我尝试下载了lombok（没用），版本jdk20

**Comment by UsamiCake** [comment]
lombok版本太低，jdk16以上的都运行不了，在配置里把lombok的版本改成最新的，网上有教程
